FROM rocm/dev-ubuntu-24.04:7.1-complete

RUN apt update
RUN apt install -y python3 python3-pip python3-venv python3-dev
RUN apt install -y build-essential libffi-dev libdw1 curl git zip

# create virtual environment, the correct way https://pythonspeed.com/articles/activate-virtualenv-dockerfile/
ENV VIRTUAL_ENV=/app/venv
RUN python3 -m venv $VIRTUAL_ENV
ENV PATH="$VIRTUAL_ENV/bin:$PATH"

WORKDIR /app

# install jax with ROCM support https://github.com/jax-ml/jax/blob/main/build/rocm/README.md
RUN pip3 install --upgrade jax[rocm7-local]
RUN pip3 install flax optax orbax-checkpoint
RUN pip3 install debugpy

CMD ["python3", "-m", "debugpy", "--listen", "0.0.0.0:43690", "tasks/benchmark.py"]